- id: cargo-sort-fix
  name: Check Cargo.toml is sorted
  description: 'Ensure Cargo.toml is sorted'
  entry: cargo-sort-fix
  language: rust
  types: [file, toml]
  files: Cargo\.toml
  pass_filenames: false
